controllers:
  resource: ../../src/Controller/
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation

api_secrets:
  resource: ../../src/Controller/Api/Secrets
  type: annotation
  prefix: '/api/secrets'
